name: 02-Matrix

on:
    push:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-versions: [2.7, 3.9]

        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            # Rather than manually installing with repos
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Run the script with the specific version
              run: |
                  python -V
                  python test.py
