name: 05.1-Working with single Docker container

on: push

jobs:
    linux:
        runs-on: ubuntu-latest
        container: "appsecco/dvna:sqlite"

        steps:
            - name: Start the DVNA container and check if it did
              run: |
                  id
                  uname -a
                  ls -la 
                  pwd
                  cd /app/
                  ls -la
                  node -v

            - name: ZAP Scan
              uses: zaproxy/action-full-scan@v0.1.0
              with:
                  target: "http://127.0.0.1:9090"
