name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container: "node:current"

        steps:
            - uses: actions/checkout@v1
            - run: |
                  npm ci
                  npm run build
                  npm test
